BOT_NAME = "north_dakota_sos_crawler"

SPIDER_MODULES = ["north_dakota_sos_crawler.spiders"]
NEWSPIDER_MODULE = "north_dakota_sos_crawler.spiders"

ROBOTSTXT_OBEY = False
DOWNLOAD_DELAY = 4
CONCURRENT_REQUESTS_PER_DOMAIN = 1
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 5
AUTOTHROTTLE_MAX_DELAY = 60
AUTOTHROTTLE_TARGET_CONCURRENCY = .5
HTTPCACHE_ENABLED = True
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"
